# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
<<<<<<< HEAD
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    
# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config
=======
    config: './rubocop.yml'

# add the files here you want to be ignored by stylelint
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

>>>>>>> 9adf9cc418a5cf181686ce9ce32d5548f1360f4e
# find full documentation here: https://stickler-ci.com/docs